### ISSUE TITLE
Customize default message

### ISSUE THREAD

**Issue by jupl** [tmux-plugins/tmux-prefix-highlight#14]
Right now it shows nothing. It would be great to allow a custom default value to show up. For instance, it would be useful to put blank spaces by default. I have status centered and it's annoying when I hit the prefix everything shifts. Another reason is how like in some Vim customizations you can show the current state at any time, including normal state.

**Comment by lonix1** [comment]
Already possible, from the main readme:

> The empty (shown when prefix is off) prompt and attribute can be configured, It is useful for aligning segments.
set -g @prefix_highlight_empty_prompt '        '          # default is '' (empty char)
set -g @prefix_highlight_empty_attr 'fg=default,bg=green' # default is 'fg=default,bg=default'

Issue can be closed?

**Comment by amirrezasadeqi** [comment]
it solves the problem. i tested it on my configs and it works.

**Comment by erickpintor** [comment]
Thank you all! I'm closing this issue for now.
