### ISSUE TITLE
Highlight should reset colours

### ISSUE THREAD

**Issue by arunjit** [tmux-plugins/tmux-prefix-highlight#2]
The colours used in the highlighting affect the rest of the status bar, which doesn't have specific colours set.

Without the plugin loaded:
![screen shot 2015-11-14 at 20 21 16](https://cloud.githubusercontent.com/assets/1237549/11164132/03af421c-8b0e-11e5-80f9-080dfea856a1.png)

With `#{prefix_highlight}` in the status:
![screen shot 2015-11-14 at 20 22 31](https://cloud.githubusercontent.com/assets/1237549/11164133/03b079e8-8b0e-11e5-8594-b9dd9ea3548d.png)

My setting for the right status:
`set -g status-right "#{prefix_highlight} %H:%M | %Y-%m-%d "`

**Comment by erickpintor** [comment]
Hi @arunjit, thanks for reporting the issue.

The commit https://github.com/tmux-plugins/tmux-prefix-highlight/commit/448fc656a13383826249d1a8ea808da5c606d3c7 seems to fix the problem. Would you mind to update and test it again, please?

**Comment by arunjit** [comment]
Yup! This works as expected now, thanks!
