### ISSUE TITLE
Background color not changing

### ISSUE THREAD

**Issue by cbows** [tmux-plugins/tmux-prefix-highlight#24]
Background color of prefix highlight prompt is not changing.
It worked before 8d833fbba98528120b75fb930aa8892e0c5cafdc

I am using tmux 2.8 and have the following settings:

```tmux
set -g @prefix_highlight_fg 'colour237'
set -g @prefix_highlight_bg 'colour109'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=colour237,bg=colour214'
set -g @prefix_highlight_empty_prompt '    '

set -g status-right '#{prefix_highlight} ME ...
```

Prompt (should have default background color):
![image](https://user-images.githubusercontent.com/32486983/76004747-4cbd2f80-5f0a-11ea-947f-e2ecd27129b0.png)

Copy mode also looks weird:
![image](https://user-images.githubusercontent.com/32486983/76006113-4c259880-5f0c-11ea-9f90-f4f632787d74.png)

**Comment by cbows** [comment]
262d6101776d3f37fae612dae62db137f35f2885 fixes it.

**Comment by erickpintor** [comment]
Thank you for tracking this. That commit has been merged. I'll close this issue for now.
