### ISSUE TITLE
Not working anymore after #21

### ISSUE THREAD

**Issue by MunifTanjim** [tmux-plugins/tmux-prefix-highlight#26]
#21 broke it

![Screenshot from 2020-03-26 05-45-47](https://user-images.githubusercontent.com/8050659/77596069-1da44780-6f25-11ea-9c92-a3c43998b0ce.png)

Instead of applying the `_attr` values, it now prints them.

**Comment by Blake-LeBlanc** [comment]
Thanks @MunifTanjim ! I'm having this issue as well, glad to see you're on the ball with a fix coming soon 👍
