### ISSUE TITLE
Optional prefix_highlight separator

### ISSUE THREAD

**Issue by ethagnawl** [tmux-plugins/tmux-prefix-highlight#7]
It'd be nice to be able to plug in a separator that'd appear before/after the contents of prefix_highlight.

For instance, I'd like my status bar to appear like this when prefix_highlight is inactive:

Batt: ❇  99% 

and like this when prefix_highlight is active:

^B | Batt: ❇  99% 

If you'd be open to accepting a PR, I'd be happy to take a pass at implementing this.

**Comment by erickpintor** [comment]
Thanks @ethagnawl. That's a great idea.
If you want to implement it, please go ahead. I'll be happy to review your PR.

**Comment by erickpintor** [comment]
Implemented as part of #8
